// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Severity } from "./Severity";

/**
 * Something worth interrupting the user for. Only ever emitted on a severity
 * *increase* — see [`Hub::alerts_for`].
 */
export type Alert = { at: string, provider: string, provider_label: string, meter: string, meter_label: string, severity: Severity, 
/**
 * Ready to use as a notification body.
 */
message: string, };
