// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthPreference } from "./AuthPreference";
import type { LoginKind } from "./LoginKind";
import type { TokenPrompt } from "./TokenPrompt";

/**
 * One way of authenticating, in the UI's terms rather than the protocol's.
 */
export type AuthMethod = { auth: AuthPreference, kind: LoginKind, label: string, 
/**
 * What actually happens, in one line. The user is picking between
 * "browser" and "borrow the CLI's token" and deserves to know the
 * difference before clicking.
 */
detail: string, 
/**
 * The adapter's own default — rendered as "Recommended".
 */
recommended: boolean, 
/**
 * False when this machine cannot use it: no vendor CLI installed, say.
 * Still listed, because *why* it is unavailable is the useful part.
 */
available: boolean, unavailable_reason?: string, 
/**
 * Present only for [`LoginKind::Paste`].
 */
token?: TokenPrompt, };
