// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which auth mechanism a provider should use, from config.
 */
export type AuthPreference = "delegated" | "own" | "token";
