// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthPreference } from "./AuthPreference";

export type ConfiguredProvider = { id: string, label: string, 
/**
 * Same `data:` URI the catalogue carries — see [`ProviderInfo::icon`].
 */
icon: string, auth: AuthPreference, enabled: boolean, 
/**
 * Whether a credential exists — not whether it still works. The provider
 * tile answers the second question; this one decides whether the row
 * offers "Sign in" or "Signed in".
 */
signed_in: boolean, 
/**
 * Why it is not signed in, when there is something useful to say.
 */
note?: string, };
