// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the UI has to *do* for a method. The three shapes need three different
 * screens, and this is the only thing the frontend switches on.
 */
export type LoginKind = "browser" | "paste" | "borrow";
