// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Phase } from "./Phase";

/**
 * What a started login tells the client.
 */
export type LoginStarted = { 
/**
 * Echoed back when posting the code, so a stale tab cannot finish someone
 * else's login.
 */
session: string, phase: Phase, };
