// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Period } from "./Period";

export type MeterKind = { "type": "window", used_pct: number, resets_at: string | null, window_mins: number | null, } | { "type": "balance", amount: number, currency: string, of_total: number | null, unlimited: boolean, } | { "type": "spend", amount: number, currency: string, period: Period, };
