// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MeterKind } from "./MeterKind";
import type { Severity } from "./Severity";

export type Meter = { id: string, label: string, kind: MeterKind, severity: Severity, };
