// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a login has got to. Polled by `GET`, and pushed over SSE.
 */
export type Phase = { "phase": "opening" } | { "phase": "waiting", authorize_url: string, 
/**
 * The provider will show a code rather than redirect; the UI must
 * offer a field and post it back.
 */
needs_code: boolean, } | { "phase": "done" } | { "phase": "failed", message: string, };
