// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthMethod } from "./AuthMethod";

/**
 * One provider, as the "Add provider" screen sees it.
 */
export type ProviderInfo = { id: string, label: string, 
/**
 * One line, shown under the name in the picker.
 */
summary: string, 
/**
 * Tile accent as a CSS hex colour, so a list of providers is scannable by
 * shape rather than by reading every label.
 */
accent: string, docs_url?: string, 
/**
 * Every way in to this provider, best first. Never empty — a provider
 * with no way to authenticate could not have an adapter.
 */
methods: Array<AuthMethod>, };
