// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfiguredProvider } from "./ConfiguredProvider";
import type { ProviderInfo } from "./ProviderInfo";

/**
 * Everything the config screen renders from.
 */
export type ProvidersView = { 
/**
 * Every provider that *could* be added, with its login methods. Built
 * from the adapters themselves, so a new provider appears here — and
 * therefore in the UI — without a line of frontend changing.
 */
catalogue: Array<ProviderInfo>, 
/**
 * What the user has actually added, in the order they are displayed.
 */
configured: Array<ConfiguredProvider>, };
