// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthMethod } from "./AuthMethod";

/**
 * One provider, as the "Add provider" screen sees it.
 */
export type ProviderInfo = { id: string, label: string, 
/**
 * One line, shown under the name in the picker.
 */
summary: string, 
/**
 * The provider's own mark, as a `data:` URI.
 *
 * Inlined rather than linked because the panel's CSP is
 * `img-src 'self' data:`: an `http://localhost:<port>/icon` would be
 * blocked outright, and even allowed it would leave a row of broken
 * squares whenever the daemon was slow or on another machine. A name is
 * read; a mark is recognised, which is the whole point of putting one
 * next to a list of four near-identical rows.
 */
icon: string, docs_url?: string, 
/**
 * Every way in to this provider, best first. Never empty — a provider
 * with no way to authenticate could not have an adapter.
 */
methods: Array<AuthMethod>, };
