// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthKind } from "./AuthKind";
import type { Meter } from "./Meter";
import type { Status } from "./Status";

export type Provider = { id: string, label: string, 
/**
 * Subscription tier as the provider names it: "pro", "plus", …
 */
plan: string | null, status: Status, 
/**
 * How this provider's credential was obtained, so the UI can show it.
 */
auth: AuthKind, updated_at: string, meters: Array<Meter>, };
