// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Provider } from "./Provider";

export type Snapshot = { generated_at: string, providers: Array<Provider>, };
