// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Status = { "state": "ok" } | { "state": "stale", since: string, } | { "state": "error", message: string, } | { "state": "unavailable", reason: string, };
