// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How to label and explain a pasted secret.
 *
 * Every provider words this differently — one wants an API key from a web
 * console, another wants the output of a CLI command — and getting it wrong
 * sends the user hunting through the wrong settings page.
 */
export type TokenPrompt = { 
/**
 * What to call the button: "Paste an API key".
 *
 * Spelled out per provider rather than composed from `label`. Building it
 * produced "Paste an api key" — English articles and capitalisation do not
 * survive `to_lowercase`, and a wrong-sounding button is exactly the kind
 * of thing that makes a setup screen feel unfinished.
 */
action: string, 
/**
 * Field label: "API key", "Token".
 */
label: string, placeholder: string, 
/**
 * One line on where to get it.
 */
help: string, 
/**
 * A page to open, when there is one to open.
 */
url?: string, };
